<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jkrv_theme"
 *
 * Auto generated by Extension Builder 2017-02-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'JKRV Website-Template',
    'description' => '',
    'category' => 'distribution',
    'author' => 'Sebastian Jung',
    'author_email' => 'jung.jena@gmx.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.9.99',
            'version' => '',
            'recycler' => '',
            'filemetadata' => '',
            'powermail' => '',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
